apiVersion: v1
kind: Service
metadata:
  name: url-shortener-redis-service
  labels:
    app: url-shortener-redis
spec:
  ports:
    - port: 80
      targetPort: 6379
      protocol: TCP 
  selector:
    matchLabels:
      app: url-shortener-redis